name: face_net_authentication
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.1+13

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.4
  tflite_flutter: ^0.9.0
  camera: ^0.11.0+1
  path_provider: ^2.0.9
  path: ^1.8.0
  google_ml_kit: ^0.13.0
  image: ^3.0.2
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.2.4
  sqflite: ^2.0.2
  get_it: ^7.2.0
  # intl: ^0.18.1
  intl: ^0.17.0
  fluttertoast: ^8.2.2
  rflutter_alert: ^2.0.7
  # location: ^5.0.3
  # trust_location: ^2.0.13
  dio: ^5.4.3+1
  latlong2: ^0.9.1
  # change_app_package_name: ^1.1.0
  device_info_plus: ^9.0.3
  sn_progress_dialog: ^1.1.3
  geocoding: ^3.0.0
  # internet_connection_checker: ^1.0.0+1
  geolocator: ^12.0.0
  one_clock: ^1.0.8
  shared_preferences: ^2.2.3
  # lazy_load_scrollview: ^1.3.0
  # any_animated_button: ^0.0.4
  progress_state_button: ^1.0.4
  package_info_plus: ^4.1.0
  lottie: ^2.6.0
  # code_input: ^2.0.0
  # flutter_pin_code_widget: ^0.1.0
  pinput: ^3.0.1
  restart_app: ^1.2.1
  # flutter_launcher_icons: ^0.11.0
  # device_imei: ^0.0.4+2
  unique_identifier: ^0.3.0
  # uuid: ^4.2.1
  kiosk_mode: ^0.5.0+2
  flutter_easyloading: ^3.0.5
  # permission_handler: ^11.1.0
  # get_mac_address: ^0.0.2
  imei: ^0.0.1
  flutter_udid: ^3.0.0
  # custom_date_range_picker: ^1.0.10
  # kiosk_mode: ^0.5.0+2
  # flutter_geocoder: ^0.2.2-nullsafety
  # date_time_picker: ^2.1.0
  date_picker_timeline: ^1.2.3
  connectivity_plus: ^6.0.1
  # internet_file: ^1.2.0
  flutter_cached_pdfview: ^0.4.2
  # firebase_crashlytics: ^3.5.1
  # firebase_analytics: ^10.10.1
  # onnxruntime: ^1.3.0
  order_tracker_zen: ^1.0.0+4
  timeline_tile: ^2.0.0
  audioplayers: ^6.0.0
  internet_connection_checker: ^1.0.0+1
  date_field: ^3.0.3
  # pytorch_mobile: ^0.2.2
  # pytorch_mobile: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/mobilefacenet.tflite
    # - assets/FaceAntiSpoofing.tflite
    # - assets/FaceBagNet_color_96.onnx
    # - assets/AntiSpoofing_bin_1.5_128.onnx
    # - assets/AntiSpoofing_print-replay_128.onnx
    # - assets/2.7_80x80_MiniFASNetV2.onnx
    # - assets/adziehrdy_FAS.tflite
    - assets/logo.png
    - assets/images/
    - assets/lottie/
    # - assets/FaceDeSpoofing.tflite
    # - assets/model_float32.onnx
    - assets/sound/
    # - assets/spoofnet_celeba-best.pt
  #   - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
