final mealSheetSchedule = {
  "Sahur": ["02:00", "04:00"],
  "Breakfast": ["05:00", "07:00"],
  "Lunch": ["11:30", "13:00"],
  "Dinner": ["17:00", "20:00"],
  "Supper": ["23:00", "01:00"],
};

List<String> foodAnimation = [
  "foodAnim1",
  "foodAnim2",
  "foodAnim3",
  "foodAnim4",
];
List<String> ucapanSelamatMakan = [
  "Selamat makan, rekan-rekan Pertamina! Semoga energinya kembali full untuk bekerja!",
  "Santai sejenak dan nikmati makan siang, biar makin semangat berkontribusi untuk negeri!",
  "Makan dulu, jangan sampai kehabisan tenaga saat menjaga ketahanan energi Indonesia!",
  "Selamat menikmati hidangan! Semoga makin sehat dan bertenaga untuk tugas-tugas di Pertamina!",
  "Jangan lupa doa sebelum makan, semoga rezeki kita semua terus lancar dan berkah!",
  "Makan siang dulu yuk, biar tetap fokus dan produktif dalam melayani bangsa!",
  "Isi bahan bakar perut dulu, supaya kerja makin optimal seperti kilang yang selalu beroperasi!",
  "Selamat makan siang, rekan-rekan! Tetap semangat menjaga kinerja terbaik untuk Pertamina!",
  "Jangan lupa makan yang bergizi, biar tetap sehat dan kuat dalam menjalankan tugas negara!",
  "Santai sejenak, nikmati hidangan, lalu lanjutkan tugas dengan penuh semangat!",
  "Selamat makan! Semoga hari ini penuh keberkahan dan kesuksesan dalam setiap pekerjaan kita!",
  "Makan yang cukup, jangan sampai kehabisan energi di tengah pekerjaan!",
  "Jangan buru-buru, nikmati rasa makanannya dengan syukur dan bahagia!",
  "Makan dulu biar bisa tetap semangat menjaga ketahanan energi nasional!",
  "Nikmati waktu makan siang ini sebagai momen istirahat yang berharga!",
  "Makan enak, kerja pun makin lancar! Selamat makan rekan-rekan Pertamina!",
  "Habis makan, jangan lupa cuci tangan dan tetap jaga kebersihan di area kerja!",
  "Selamat makan! Semoga selalu diberikan kesehatan untuk terus berkarya di Pertamina!",
  "Makan siang dulu biar tetap kuat menjalani tugas harian kita!",
  "Santap dengan tenang, nikmati setiap rasa sebagai bentuk rasa syukur!",
  "Selamat makan! Semoga makanannya lezat dan energinya kembali penuh!",
  "Makan yang bergizi, jangan lupa sayurnya biar tetap sehat dan bugar!",
  "Makan siang dengan rekan kerja lebih seru dan menyenangkan!",
  "Tetap jaga kesehatan dengan makan yang cukup dan minum air putih!",
  "Makan dulu biar nggak cranky saat rapat sore nanti!",
  "Selamat makan rekan-rekan! Semoga makin semangat dalam bekerja dan berkarya!",
  "Jangan sampai telat makan ya, biar nggak sakit dan bisa terus aktif berkontribusi!",
  "Selamat menikmati makan siang, semoga makin produktif dalam tugas-tugas hari ini!",
  "Makan dulu, nanti baru lanjut memberikan yang terbaik untuk perusahaan!",
  "Makan dulu yuk, biar energi kembali full untuk lanjut kerja!",
  "Jangan lupa bersyukur atas makanan yang ada, selamat makan semuanya!",
  "Makan yang cukup, jangan terlalu kenyang biar nggak ngantuk di siang hari!",
  "Makan enak, hati pun senang! Selamat makan rekan-rekan!",
  "Isi energi dulu dengan makanan yang lezat dan bergizi!",
  "Nikmati makan siang sebagai waktu rehat yang menyenangkan!",
  "Jangan lupa minum juga! Tetap terhidrasi agar tetap segar dalam bekerja!",
  "Makan siang dulu biar tenaga tetap terjaga sampai sore nanti!",
  "Makan bareng rekan kerja, bikin makin akrab dan solid!",
  "Makan dulu, tugas bisa lanjut nanti dengan semangat baru!",
  "Habis makan, lanjut kerja dengan semangat 100%!",
  "Selamat makan siang! Semoga makin sukses dalam setiap pekerjaan kita!",
  "Nikmati makan siang dengan tenang, jangan terlalu buru-buru!",
  "Makan dengan senyum, rasanya lebih nikmat!",
  "Jangan main HP terus, fokus nikmati makananmu!",
  "Makan dulu, nanti lanjut lagi membangun energi negeri!",
  "Jangan lupa habiskan makananmu, hargai setiap rezeki yang ada!",
  "Selamat makan, semoga makin produktif dalam kerja dan tetap semangat!",
  "Makan dulu biar nggak lemas di sore hari!",
  "Makan yang sehat, biar tubuh tetap bugar dan siap menghadapi tantangan kerja!",
  "Makan enak, semangat kerja pun meningkat!",
  "Isi ulang tenaga sebelum kembali ke lapangan!",
  "Habis makan jangan lupa olahraga ringan biar tetap fit!",
  "Makan dengan penuh rasa syukur, semoga makin berkah rezekinya!",
  "Selamat makan! Tetap semangat memberikan kontribusi terbaik untuk negeri!",
  "Jangan sampai kelaparan, makanlah tepat waktu agar tetap prima!",
  "Makan bersama rekan kerja bikin suasana makin akrab dan harmonis!",
  "Makan dulu, lalu kembali berkarya dengan semangat baru!",
  "Selamat makan, semoga harimu selalu menyenangkan!",
  "Jangan lupa nikmati makanannya, jangan terburu-buru!",
  "Makan dulu yuk, biar nggak lemes saat bekerja!",
  "Habis makan lanjut kerja dengan lebih fokus dan produktif!",
  "Nikmati setiap gigitan dengan bahagia!",
  "Makan yang cukup, jangan sampai sakit karena telat makan!",
  "Makan siang dulu, baru lanjut meeting dengan semangat!",
  "Hargai waktu makan sebagai waktu istirahat sejenak dari kesibukan!",
  "Makan enak, hati tenang, kerja lancar!",
  "Makan dulu yuk, biar makin happy dan semangat!",
  "Makan malam yang hangat bikin hati nyaman setelah seharian kerja!",
  "Jangan skip makan ya, biar tubuh tetap sehat dan kuat!",
  "Makan siang sambil santai biar lebih nikmat!",
  "Jangan terlalu banyak mikirin kerjaan, makan dulu yuk!",
  "Habis makan jangan lupa senyum!",
  "Makan malam bareng keluarga setelah seharian kerja bikin hati tenang!",
  "Makan dulu, nanti baru lanjut ngerjain laporan!",
  "Jangan lupa tambahin sambal biar makin mantap!",
  "Makan siang dulu biar nggak loyo pas kerja sore!",
  "Jangan tinggalkan makanan di piring, hargai setiap rezeki yang ada!",
  "Makan sehat, kerja makin kuat!",
  "Selamat makan! Semoga harimu penuh berkah dan kebahagiaan!",
  "Makan dulu yuk, biar lebih fresh pas balik kerja!",
  "Jangan buru-buru habisin makanan, nikmati setiap suapan!",
  "Selamat makan rekan-rekan Pertamina, terus semangat berkarya!"
];
List<String> ucapanPolaMakanSehat = [
  "Jaga pola makanmu, tubuh sehat akan membantumu tetap produktif!",
  "Makan yang teratur dan bergizi adalah investasi untuk kesehatan jangka panjang!",
  "Jangan lupa sarapan! Itu adalah sumber energi utama untuk memulai hari dengan semangat!",
  "Kurangi makanan berlemak, perbanyak sayur dan buah biar tubuh tetap fit!",
  "Minum air putih yang cukup, jangan sampai dehidrasi saat bekerja!",
  "Jangan terlalu sering makan junk food, pilih makanan sehat untuk tubuh yang lebih bertenaga!",
  "Pola makan yang baik membantu meningkatkan fokus dan daya tahan tubuh!",
  "Ingat! Tubuh kita butuh nutrisi, bukan cuma rasa enak!",
  "Jaga pola makanmu sekarang, supaya nanti tidak perlu repot mengurus kesehatanmu!",
  "Makan secukupnya, jangan berlebihan, supaya tetap bugar sepanjang hari!",
  "Jangan terlalu banyak gula, karena kesehatan lebih penting daripada rasa manis sesaat!",
  "Jangan nunggu lapar banget baru makan, jaga jam makan yang teratur ya!",
  "Pilih makanan yang baik untuk tubuhmu, karena sehat itu lebih nikmat daripada sekadar kenyang!",
  "Mulai hari dengan makanan sehat agar lebih produktif dan bersemangat!",
  "Jangan biasakan makan malam terlalu larut, biar tidurmu lebih nyenyak dan badan tetap fit!",
  "Makan dengan porsi yang pas, jangan sampai kekenyangan dan jadi malas gerak!",
  "Sayangi tubuhmu dengan memberi asupan yang baik setiap harinya!",
  "Jangan melewatkan waktu makan, tubuh butuh energi untuk terus beraktivitas!",
  "Jaga pola makan seimbang, supaya kerja makin lancar dan tubuh tetap kuat!",
  "Makan bukan sekadar kenyang, tapi juga untuk kesehatan jangka panjang!",
  "Jangan terlalu sering makan gorengan, pilih yang lebih sehat seperti rebusan atau panggangan!",
  "Pilih makanan yang bernutrisi tinggi supaya daya tahan tubuh tetap terjaga!",
  "Jangan lupakan protein dalam menu harianmu, biar otot tetap kuat dan sehat!",
  "Ingat! Sehat itu mahal, jadi lebih baik menjaga daripada mengobati!",
  "Kurangi makanan instan, perbanyak makanan alami yang lebih sehat!",
  "Makanlah dengan porsi yang wajar, karena kelebihan makan bisa membuat tubuh mudah lelah!",
  "Jangan lupa makan buah setiap hari, supaya tubuh lebih segar dan bertenaga!",
  "Kunyah makanan dengan baik, jangan terburu-buru, agar pencernaan bekerja lebih maksimal!",
  "Kurangi minuman manis, perbanyak air putih agar tubuh lebih sehat dan segar!",
  "Jangan sering makan berlebihan saat stress, lebih baik kelola stress dengan baik!",
  "Makan dengan porsi kecil tapi sering lebih baik daripada makan dalam jumlah besar sekaligus!",
  "Perhatikan gizi dalam setiap makananmu, jangan hanya tergoda rasa!",
  "Jangan biarkan pekerjaan membuatmu lupa makan, jaga kesehatan selalu!",
  "Ganti camilanmu dengan yang lebih sehat, seperti kacang-kacangan atau yogurt!",
  "Kurangi garam dalam makananmu, biar tekanan darah tetap stabil dan tubuh lebih sehat!",
  "Pilih makanan yang kaya serat agar pencernaan lebih lancar!",
  "Sarapan itu penting! Jangan pernah melewatkan makanan pertama di pagi hari!",
  "Kesehatan dimulai dari pola makan yang baik, yuk mulai sekarang!",
  "Nikmati makananmu dengan penuh kesadaran, jangan makan sambil main HP!",
  "Pilih makanan yang membuatmu lebih sehat, bukan hanya yang membuatmu kenyang!",
  "Makanlah sesuai kebutuhan, jangan berlebihan agar tubuh tetap fit!",
  "Cintai tubuhmu dengan memberi nutrisi terbaik setiap harinya!",
  "Jangan biarkan kesibukan membuatmu mengabaikan pola makan yang sehat!",
  "Jaga pola makan agar tubuh selalu dalam kondisi prima untuk beraktivitas!",
  "Konsumsi makanan sehat hari ini, tubuhmu akan berterima kasih di kemudian hari!",
  "Makan makanan sehat adalah bentuk self-care yang terbaik!",
  "Tetap semangat menjaga pola makan, demi kesehatan yang lebih baik!",
  "Jangan pernah menunda makan, tubuhmu butuh asupan energi yang cukup!",
  "Jaga kesehatanmu dengan pola makan yang baik, karena tubuh sehat adalah aset berharga!",
  "Makanan yang baik memberikan energi positif untuk aktivitasmu sehari-hari!",
  "Kurangi makan di luar, lebih baik masak sendiri agar lebih sehat dan terjamin gizinya!",
  "Makan tepat waktu itu penting, jangan sampai telat terus ya!",
  "Makan dengan gizi seimbang bikin badan tetap segar dan bugar sepanjang hari!",
  "Ingat, tubuhmu adalah cerminan dari pola makanmu sehari-hari!",
  "Jangan biasakan makan tengah malam, biar pencernaan tetap sehat!",
  "Makan sehat sekarang, agar di masa depan kamu tetap aktif dan berenergi!",
  "Kurangi makanan berminyak, supaya tubuh tetap ringan dan sehat!",
  "Gantilah nasi putih dengan nasi merah atau sumber karbohidrat kompleks lainnya!",
  "Biasakan makan sayur dan buah setiap hari, karena kaya akan vitamin dan mineral!",
  "Makanlah dengan bahagia, karena suasana hati yang baik juga mempengaruhi kesehatanmu!",
  "Makan sehat bukan berarti membosankan, banyak pilihan makanan enak yang tetap sehat!",
  "Mulai ubah pola makanmu dari sekarang, jangan tunggu sampai sakit datang!",
  "Tetap jaga pola makan meskipun sibuk, kesehatanmu adalah prioritas!",
  "Jangan makan terburu-buru, beri waktu tubuhmu untuk menikmati makanan dengan baik!",
  "Jangan terlalu banyak ngemil yang tidak sehat, lebih baik konsumsi buah-buahan!",
  "Jaga kesehatan pencernaan dengan makan makanan yang kaya serat!",
  "Hindari makanan yang terlalu banyak pengawet dan pemanis buatan!",
  "Makanlah sesuai kebutuhan, bukan sekadar karena lapar mata!",
  "Makan sehat adalah langkah kecil menuju hidup yang lebih bahagia!",
  "Sehat itu pilihan, jadi mulai jaga pola makan dari sekarang!",
  "Jangan biasakan makan di depan layar, nikmati makanan dengan lebih sadar!",
  "Hindari makan sebelum tidur, beri waktu tubuh untuk mencerna makanan!",
  "Jaga pola makanmu, karena makanan yang sehat akan membantumu tetap berenergi!",
  "Tubuh yang sehat adalah hasil dari makanan yang baik dan bergizi!",
  "Makan dengan teratur akan membuat metabolisme tubuh lebih baik!",
  "Mulailah hari dengan sarapan sehat, agar harimu lebih produktif dan menyenangkan!",
  "Hidup sehat dimulai dari pola makan yang benar!",
  "Jaga pola makanmu, karena kesehatan adalah aset yang paling berharga!",
  "Kesehatan dimulai dari apa yang kita makan setiap hari!",
  "Yuk, mulai pola makan sehat agar tubuh lebih kuat dan bugar!",
  "Pilih makanan yang memberi manfaat untuk tubuhmu, bukan sekadar yang enak di lidah!"
];
final List<String> mealTips = [
  "Sarapan adalah kunci untuk memulai hari dengan penuh energi. Jangan lewatkan sarapan karena tubuh membutuhkan bahan bakar untuk bekerja secara optimal. Pilih menu yang kaya serat dan protein seperti oatmeal dengan buah atau roti gandum dengan telur. Dengan sarapan yang baik, kamu akan lebih fokus dan tidak mudah lapar sebelum jam makan siang tiba.",
  "Makan siang adalah waktu yang penting untuk mengisi ulang energi tubuh. Pilih makanan dengan keseimbangan karbohidrat kompleks, protein, dan lemak sehat agar tetap bertenaga hingga sore hari. Hindari makanan yang terlalu berminyak atau tinggi gula karena bisa membuatmu mengantuk setelah makan siang. Cobalah membawa bekal dari rumah untuk memastikan nutrisi yang masuk ke tubuh lebih terkontrol.",
  "Minum cukup air putih sangat penting agar tubuh tetap terhidrasi selama bekerja. Dehidrasi dapat menyebabkan kelelahan, pusing, dan menurunkan produktivitas. Usahakan minum minimal delapan gelas air sehari. Jika sulit mengingat, gunakan botol air dengan tanda waktu atau setel pengingat di ponsel agar tidak lupa minum air.",
  "Hindari makanan cepat saji yang tinggi lemak trans dan gula tambahan. Makanan seperti burger, kentang goreng, atau ayam goreng mungkin praktis, tetapi sering kali mengandung kalori kosong tanpa nutrisi yang cukup. Jika terpaksa membeli makanan di luar, pilih opsi yang lebih sehat seperti salad dengan protein atau nasi dengan lauk rendah lemak.",
  "Camilan sehat bisa menjadi solusi agar tidak kelaparan di antara waktu makan. Pilih camilan yang tinggi serat dan protein seperti almond, yogurt tanpa gula, atau buah segar. Hindari camilan tinggi gula seperti biskuit manis atau keripik yang hanya akan meningkatkan kadar gula darah secara tiba-tiba dan menyebabkan rasa lapar kembali dengan cepat.",
  "Kurangi konsumsi minuman berkafein berlebihan. Kopi memang bisa membantu meningkatkan fokus, tetapi terlalu banyak kafein dapat menyebabkan gangguan tidur dan dehidrasi. Coba ganti kopi dengan teh hijau atau teh herbal yang lebih ringan dan memiliki manfaat kesehatan lainnya seperti meningkatkan metabolisme dan mengurangi stres.",
  "Makan dalam porsi kecil tetapi sering dapat membantu menjaga energi tetap stabil sepanjang hari. Pola makan ini juga dapat mencegah makan berlebihan di waktu makan utama. Cobalah untuk mengonsumsi tiga kali makan utama dan dua kali camilan sehat agar tubuh tetap mendapatkan asupan nutrisi yang cukup.",
  "Jangan makan terlalu malam, terutama menjelang tidur. Makan malam yang terlalu dekat dengan waktu tidur dapat menyebabkan gangguan pencernaan dan kualitas tidur yang buruk. Usahakan makan malam setidaknya dua hingga tiga jam sebelum tidur dan pilih makanan yang mudah dicerna seperti sup sayur atau protein tanpa lemak.",
  "Perbanyak konsumsi sayuran dan buah-buahan dalam setiap hidangan. Sayuran kaya akan serat, vitamin, dan mineral yang dibutuhkan tubuh untuk bekerja secara optimal. Jika sulit mengonsumsi sayur dalam jumlah besar, coba buat smoothie dengan campuran buah dan sayuran agar lebih mudah dikonsumsi.",
  "Gunakan piring kecil saat makan untuk membantu mengontrol porsi. Piring yang lebih besar sering kali membuat kita mengambil makanan lebih banyak dari yang dibutuhkan. Dengan menggunakan piring kecil, secara psikologis kamu akan merasa sudah makan dalam porsi cukup, padahal sebenarnya jumlahnya lebih sedikit.",
  "Kurangi konsumsi gula tambahan dalam makanan dan minuman. Gula berlebih dapat meningkatkan risiko obesitas, diabetes, dan penyakit jantung. Jika suka minuman manis, coba ganti dengan infused water atau teh herbal tanpa gula. Untuk makanan, pilih pemanis alami seperti madu atau kurma sebagai alternatif yang lebih sehat.",
  "Hindari makan sambil bekerja atau menonton. Fokuslah pada makanan saat makan agar lebih sadar dengan apa yang dikonsumsi. Makan sambil melakukan aktivitas lain sering kali menyebabkan kita makan berlebihan tanpa sadar. Dengan mindful eating, kamu bisa menikmati makanan dengan lebih baik dan lebih mudah mengenali rasa kenyang.",
  "Pastikan tubuh mendapatkan cukup serat setiap hari. Serat penting untuk menjaga pencernaan tetap sehat dan membantu mengontrol rasa lapar lebih lama. Sumber serat yang baik antara lain sayuran hijau, buah-buahan, biji-bijian utuh, dan kacang-kacangan. Jika sulit memenuhi kebutuhan serat, coba tambahkan chia seeds atau flaxseeds ke dalam makanan.",
  "Siapkan makanan sendiri sebanyak mungkin agar lebih sehat dan hemat. Membawa bekal dari rumah memungkinkan kamu untuk mengontrol bahan dan cara memasaknya. Selain itu, makanan buatan sendiri biasanya lebih bernutrisi dan bebas dari bahan tambahan berbahaya seperti pengawet dan MSG.",
  "Batasi konsumsi makanan olahan dan instan yang mengandung banyak garam dan pengawet. Makanan seperti mie instan, sosis, atau makanan kalengan memang praktis, tetapi sering kali rendah nutrisi dan tinggi natrium yang bisa menyebabkan tekanan darah tinggi. Sebisa mungkin, pilih makanan segar yang lebih alami dan sehat.",
  "Pastikan mendapatkan cukup asupan protein untuk menjaga massa otot dan stamina. Sumber protein yang baik meliputi ikan, ayam, telur, tahu, tempe, dan kacang-kacangan. Protein juga membantu menjaga rasa kenyang lebih lama sehingga bisa mengurangi keinginan untuk ngemil yang tidak sehat.",
  "Gunakan teknik memasak yang lebih sehat seperti merebus, mengukus, atau memanggang dibandingkan menggoreng. Makanan yang digoreng sering kali mengandung lemak jenuh tinggi yang tidak baik untuk kesehatan jantung. Jika tetap ingin menggoreng, gunakan minyak sehat seperti minyak zaitun atau minyak kelapa dalam jumlah yang sedikit.",
  "Jangan lupa untuk tetap aktif bergerak di sela-sela pekerjaan. Duduk terlalu lama bisa menyebabkan metabolisme melambat dan meningkatkan risiko obesitas. Coba lakukan peregangan ringan atau berjalan sebentar setiap satu jam sekali agar tubuh tetap aktif dan metabolisme tetap berjalan dengan baik.",
  "Hindari stres berlebihan yang bisa memicu makan emosional. Banyak orang cenderung makan berlebihan saat stres, terutama makanan tinggi gula dan lemak. Temukan cara lain untuk mengelola stres seperti meditasi, olahraga, atau mendengarkan musik agar pola makan tetap sehat dan terkontrol."
];
